// EOCP algorithm cases generated from eocpAlgs.csv
export interface EOCPAlg {
  id: string
  label: string
  state?: string
  caseId?: string
  algs: { moves: string; name?: string }[]
  stm?: number
  qtm?: number
  subcaseFrequency?: string
  totalFrequency?: string
  eo_case?: string
}

export const eocpAlgs: EOCPAlg[] = [
  {
    id: 'EOCP-00',
    label: 'Solved',
    state: 'Solved',
    eo_case: 'Solved',
    caseId: 'C',
    algs: [{ moves: "U U'", name: 'Skip' }],
    stm: 0,
    qtm: 0,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
  {
    id: 'EOCP-01',
    label: 'FL BL swap',
    eo_case: 'Solved',
    caseId: 'L',
    algs: [{ moves: "R U' L' U R' U' L" }],
    stm: 7,
    qtm: 7,
    subcaseFrequency: '66.67%',
    totalFrequency: '13.33%',
  },
  {
    id: 'EOCP-02',
    label: 'Diag Swap',
    eo_case: 'Solved',
    caseId: 'D',
    algs: [{ moves: "Rw U2' R2 F R F' Lw F2' L'" }],
    stm: 14,
    qtm: 14,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
  {
    id: 'EOCP-03',
    label: 'Correctly Permuted',
    eo_case: 'UF, UR',
    caseId: 'C',
    algs: [{ moves: "r U R' U R U2 r'" }],
    stm: 7,
    qtm: 8,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-04',
    label: 'LF RF Swap - Clockwise (fixed FR)',
    eo_case: 'UF, UR',
    caseId: 'F',
    algs: [{ moves: "(R' F R F') (U' F' U F)" }],
    stm: 8,
    qtm: 8,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-05',
    label: 'RF RB swap - Counterclockwise (fixed FR)',
    eo_case: 'UF, UR',
    caseId: 'R',
    algs: [{ moves: "(F R' F' R) (U R U' R')" }],
    stm: 8,
    qtm: 8,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-06',
    label: 'BL BR Swap',
    eo_case: 'UF, UR',
    caseId: 'L',
    algs: [{ moves: "[U] (R U2 R' U2) (R' F R F')" }],
    stm: 8,
    qtm: 10,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-07',
    label: 'FL BL Swap',
    eo_case: 'UF, UR',
    caseId: 'B',
    algs: [
      { moves: "(L' U2 L U2) (L F' L' F)" },
      // { moves: "[U2] (R' U2 R U2) (R B' R' B)" }
    ],
    stm: 8,
    qtm: 10,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-08',
    label: 'Diag Swap',
    eo_case: 'UF, UR',
    caseId: 'D',
    algs: [{ moves: "F U R U' R' F'" }],
    stm: 6,
    qtm: 6,
    subcaseFrequency: '16.67%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-09',
    label: 'All Correct',
    eo_case: 'UF, UB',
    caseId: 'C',
    algs: [{ moves: "F (U R U' R') (U R U' R') F'" }],
    stm: 10,
    qtm: 10,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
  {
    id: 'EOCP-10',
    label: 'FL FR Swap',
    eo_case: 'UF, UB',
    caseId: 'F',
    algs: [{ moves: "(R U R' U') (R' F R F')" }],
    stm: 8,
    qtm: 8,
    subcaseFrequency: '33.33%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-11',
    label: 'FL BL Swap',
    eo_case: 'UF, UB',
    caseId: 'L',
    algs: [{ moves: "Rw U' Rw' U' Rw U Rw' (F' U F)" }],
    stm: 10,
    qtm: 10,
    subcaseFrequency: '33.33%',
    totalFrequency: '6.67%',
  },
  {
    id: 'EOCP-12',
    label: 'Diag swap',
    eo_case: 'UF, UB',
    caseId: 'D',
    algs: [{ moves: "F R U R' U' F'" }],
    stm: 6,
    qtm: 6,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
  {
    id: 'EOCP-13',
    label: 'All Correct',
    eo_case: 'UF, UR, UB, UL',
    caseId: 'C',
    algs: [{ moves: "F (R U R' U') [S] (R U R' U') F'" }, {moves: "Rw U R' U2' R U2' Rw' U2' Rw U' Rw'"}],
    stm: 11,
    qtm: 12,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
  {
    id: 'EOCP-14',
    label: 'FL FR Swap',
    eo_case: 'UF, UR, UB, UL',
    caseId: 'F',
    algs: [{ moves: "R U' R2 D' r U r' D R2 U R'" }],
    stm: 11,
    qtm: 13,
    subcaseFrequency: '66.67%',
    totalFrequency: '13.33%',
  },
  {
    id: 'EOCP-15',
    label: 'Diag swap',
    eo_case: 'UF, UR, UB, UL',
    caseId: 'D',
    algs: [{ moves: "L F R U2 R' U2 R U2 R' F' L'" }, {moves:"Rw' (D R2 U R') (U2') (R U' R2 D') Rw"}],
    stm: 11,
    qtm: 13,
    subcaseFrequency: '16.67%',
    totalFrequency: '3.33%',
  },
]
